<div class="alert alert-block alert-success">
    <h1 align="center">Pandas Trick 30</h1>
    <h3 align="center">Pandas Styling</h3>
    <h4 align="center"><a href="http://www.iran-machinelearning.ir">Soheil Tehranipour</a></h5>
</div>

A pandas dataframe is a tabular structure with rows and columns. One of the most popular environments for performing data-related tasks is Jupyter notebooks. These are web-based platform-independent IDEs. In Jupyter notebooks, the dataframe is rendered for display using HTML tags and CSS. This means that you can manipulate the styling of these web components.

### Importing the libraries

In [41]:
import pandas as pd
import numpy as np
np.random.seed(88)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[3, 3] = np.nan
df.iloc[0, 2] = np.nan
df

      A         B         C         D         E
0   1.0  0.106884       NaN  0.956563  0.068411
1   2.0  1.068514  0.997183 -0.931548  0.730430
2   3.0 -0.171214 -1.288691  1.061436 -0.040501
3   4.0 -0.903721 -1.554133       NaN  0.200526
4   5.0 -0.747329  1.068081 -0.277024  0.086557
5   6.0 -0.253221 -1.212041  0.277273  0.552219
6   7.0 -0.467743 -1.427493  0.885805  2.360634
7   8.0 -1.522006 -0.215945  0.190327  0.722256
8   9.0 -0.870716  0.101749  0.555358  0.962261
9  10.0  1.433499 -0.701818 -0.856952 -0.858158

In [42]:
pd.__version__

'1.4.4'

In [43]:
df.shape

(10, 5)

In [44]:
df.sample(3)

     A         B         C         D         E
1  2.0  1.068514  0.997183 -0.931548  0.730430
0  1.0  0.106884       NaN  0.956563  0.068411
8  9.0 -0.870716  0.101749  0.555358  0.962261

In [45]:
df.style

In [46]:
df.style.highlight_max()

In [47]:
df.style.highlight_min()

In [48]:
df.style.highlight_null(null_color="green")

In [49]:
df.style.background_gradient()

In [50]:
df.style.set_properties(**{'border': '1.3px solid green',
                          'color': 'magenta'})

In [51]:
df.style.bar()

In [52]:
df.style.set_precision(2)

C:\Users\soso\AppData\Local\Temp\ipykernel_11340\573868923.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  df.style.set_precision(2)

In [53]:
df.style.set_caption("This is Soheil Tehranipour").set_precision(2).background_gradient()

C:\Users\soso\AppData\Local\Temp\ipykernel_11340\4174542161.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  df.style.set_caption("This is Soheil Tehranipour").set_precision(2).background_gradient()

In [54]:
df.style.hide_index()

C:\Users\soso\AppData\Local\Temp\ipykernel_11340\496160328.py:1: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()

In [56]:
def highlight_mean_greater(s):
    '''
    highlight yellow is value is greater than mean else red.
    '''
    is_max = s > s.mean()
    return ['background-color: yellow' if i else 'background-color: red' for i in is_max]

In [57]:
df.style.apply(highlight_mean_greater)

<img src="https://webna.ir/wp-content/uploads/2018/08/%D9%85%DA%A9%D8%AA%D8%A8-%D8%AE%D9%88%D9%86%D9%87.png" width=50% />